[project]
name = "youtube-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytube>=15.0.0",
    "uv>=0.6.12",
    "yt-dlp>=2025.3.31",
]
